<?php
include_once("../banco/banco.php");
include_once("../funcoes/funcoes-gerais.php");
include_once("../chamadas/cabecalho-pagina.php");
include_once("../chamadas/menu.php");
include_once("../chamadas/registrar-chamada.php");
include_once("../chamadas/contador-chamada.php");
include_once("../chamadas/procurar-chamada.php");
include_once("../chamadas/ajuda.php");
include_once("../chamadas/pagina-corpo.php");
include_once("../chamadas/decisao-procura.php");
include_once("../chamadas/chamadas-gerais.php");
include_once("../chamadas/fechando-banco.php");
include_once("../chamadas/fim-corpo.php");
